### ISSUE TITLE
how to get pre selected date as date, month and year

### ISSUE THREAD

**Issue by iamrahulkumar001** [lcnvdl/cross-datepicker#1]
hello i am using this plugin in my site and i am having an issue like i want to get pre filled value as date,month and year if the values of all the initial field is balnk

data-initial-day="" data-initial-year="" data-initial-month=""

**Comment by lcnvdl** [comment]
Hi, I'm sorry for the delay. In this plugin you can't use "white" values. Always dates.

Regards,
Luciano Videla
